### ISSUE TITLE
where is rust_rv1106.tar.xz ?

### ISSUE THREAD

**Issue by SlickZhang** [yplam/rv1106-rs#1]
no packege rust_rv1106.tar.xz

**Comment by yplam** [comment]
Hi, rust_rv1106.tar.xz was build from the  rust source, maybe I will add it in the release page.

You can use https://hub.docker.com/r/yplam/rv1106-rs docker image.

**Comment by yplam** [comment]
You can download it from https://github.com/yplam/rv1106-rs/releases/tag/v0.1.0
